# Generated by Django 5.2.4 on 2026-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastorWife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default="Pastor's Wife & Co-Labourer", max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pastor_wife/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Pastor's Wife",
                'verbose_name_plural': "Pastor's Wife",
            },
        ),
    ]
